http:
  routers:
    # JASA PELAYANAN
    jenis_pelayanan_kris_1:
      rule: "PathPrefix(`/v1.0/jenispelayanan/kris/getlist`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_kris_2:
      rule: "PathPrefix(`/v1.0/jenispelayanan/kris/getall`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_kris_3:
      rule: "PathPrefix(`/v1.0/jenispelayanan/kris/getbynama/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_kris_4:
      rule: "PathPrefix(`/v1.0/jenispelayanan/kris/getbykd/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_kris_5:
      rule: "PathPrefix(`/v1.0/jenispelayanan/kris/getbykdkategoripelayanan/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_kris_6:
      rule: "PathPrefix(`/v1.0/jenispelayanan/kris/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_kris_7:
      rule: "PathPrefix(`/v1.0/jenispelayanan/kris/update`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_kris_8:
      rule: "PathPrefix(`/v1.0/jenispelayanan/kris/deletebykd/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_non_kris_1:
      rule: "PathPrefix(`/v1.0/jenispelayanan/nonkris/getlist`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_non_kris_2:
      rule: "PathPrefix(`/v1.0/jenispelayanan/nonkris/getall`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_non_kris_3:
      rule: "PathPrefix(`/v1.0/jenispelayanan/nonkris/getbynama/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_non_kris_4:
      rule: "PathPrefix(`/v1.0/jenispelayanan/nonkris/getbykd/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_non_kris_5:
      rule: "PathPrefix(`/v1.0/jenispelayanan/nonkris/getbykdkategoripelayanan/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_non_kris_6:
      rule: "PathPrefix(`/v1.0/jenispelayanan/nonkris/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_non_kris_7:
      rule: "PathPrefix(`/v1.0/jenispelayanan/nonkris/update`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    jenis_pelayanan_non_kris_8:
      rule: "PathPrefix(`/v1.0/jenispelayanan/nonkris/deletebykd/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    kategori_pelayanan_1:
      rule: "PathPrefix(`/v1.0/kategoripelayanan/getlist`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    kategori_pelayanan_2:
      rule: "PathPrefix(`/v1.0/kategoripelayanan/getbykd/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    kategori_pelayanan_3:
      rule: "PathPrefix(`/v1.0/kategoripelayanan/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    kategori_pelayanan_4:
      rule: "PathPrefix(`/v1.0/kategoripelayanan/update`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    kategori_pelayanan_5:
      rule: "PathPrefix(`/v1.0/kategoripelayanan/deletebykd/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    kategori_pelayanan_6:
      rule: "PathPrefix(`/v1.0/kategoripelayanan/getall`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    kategori_pelayanan_7:
      rule: "PathPrefix(`/v1.0/kategoripelayanan/getbystandarlayanan/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_1:
      rule: "PathPrefix(`/v1.0/paketmcu/getlist`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_2:
      rule: "PathPrefix(`/v1.0/paketmcu/getbykd/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_3:
      rule: "PathPrefix(`/v1.0/paketmcu/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_4:
      rule: "PathPrefix(`/v1.0/paketmcu/update`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_5:
      rule: "PathPrefix(`/v1.0/paketmcu/deletebykd/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_6:
      rule: "PathPrefix(`/v1.0/paketmcu/getall`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_7:
      rule: "PathPrefix(`/v1.0/paketmcu/getbynama/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_8:
      rule: "PathPrefix(`/v1.0/paketmcu/items/get-list`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_9:
      rule: "PathPrefix(`/v1.0/paketmcu/items/get-by-kd/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_10:
      rule: "PathPrefix(`/v1.0/paketmcu/items/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_11:
      rule: "PathPrefix(`/v1.0/paketmcu/items/update`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paket_mcu_12:
      rule: "PathPrefix(`/v1.0/paketmcu/items/delete-by-kd/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paketmcu_pelayanan_1:
      rule: "PathPrefix(`/v1.0/paketmcu/pelayanan/getlist`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paketmcu_pelayanan_2:
      rule: "PathPrefix(`/v1.0/paketmcu/pelayanan/getlistbykdpaketmcu/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paketmcu_pelayanan_3:
      rule: "PathPrefix(`/v1.0/paketmcu/pelayanan/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    paketmcu_pelayanan_4:
      rule: "PathPrefix(`/v1.0/paketmcu/pelayanan/deletebykd/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_parent_1:
      rule: "PathPrefix(`/v1.0/unitlayananparent/getlist`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_parent_2:
      rule: "PathPrefix(`/v1.0/unitlayananparent/getbykd/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_parent_3:
      rule: "PathPrefix(`/v1.0/unitlayananparent/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_parent_4:
      rule: "PathPrefix(`/v1.0/unitlayananparent/update`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_parent_5:
      rule: "PathPrefix(`/v1.0/unitlayananparent/deletebykd/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_parent_6:
      rule: "PathPrefix(`/v1.0/unitlayananparent/getall`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_parent_7:
      rule: "PathPrefix(`/v1.0/unitlayananparent/getbynama/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_1:
      rule: "PathPrefix(`/v1.0/unitlayanan/getlist`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_2:
      rule: "PathPrefix(`/v1.0/unitlayanan/getbykd/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_3:
      rule: "PathPrefix(`/v1.0/unitlayanan/getbykdparent/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_4:
      rule: "PathPrefix(`/v1.0/unitlayanan/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_5:
      rule: "PathPrefix(`/v1.0/unitlayanan/update`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_6:
      rule: "PathPrefix(`/v1.0/unitlayanan/deletebykd/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_7:
      rule: "PathPrefix(`/v1.0/unitlayanan/getall`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_8:
      rule: "PathPrefix(`/v1.0/unitlayanan/getbynama/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_9:
      rule: "PathPrefix(`/v1.0/unit-layanan/get-kd-unit-bpjs/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_10:
      rule: "PathPrefix(`/v1.0/unitlayanan/getlistwithfarmasi`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_layanan_1:
      rule: "PathPrefix(`/v1.0/unitlayanan/layanan/getlistbykdunitlayanan/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_layanan_2:
      rule: "PathPrefix(`/v1.0/unitlayanan/layanan/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_layanan_3:
      rule: "PathPrefix(`/v1.0/unitlayanan/layanan/deletebyidlayananlayanan/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_get_list_lampung_in:
      rule: "PathPrefix(`/v1.0/unit-layanan/get-list/lampung-in`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

    unit_layanan_daftar_poli_get_list:
      rule: "PathPrefix(`/v1.0/daftar-poli/get-list`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-jasa-pelayanan
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
        - "simrs-auth"

  services:
    service-jasa-pelayanan:
      loadBalancer:
        servers:
          - url: '{{ env "SERVICE_JASA_PELAYANAN_URL" }}'
    service-master:
      loadBalancer:
        servers:
          - url: '{{ env "SERVICE_MASTER_URL" }}'
    service-referensi:
      loadBalancer:
        servers:
          - url: '{{ env "SERVICE_REFERENSI_URL" }}'
