services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: always
    ports:
      - "9090:9080" # Port trafik utama (pengganti APISIX)
      - "18080:8080" # Port Dashboard Traefik
    volumes:
      # Agar Traefik bisa membaca container Docker lain
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # File konfigurasi utama
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      # Folder untuk file routing (perawat, dokter, dev, prod)
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./access_logs:/var/log/traefik
    env_file:
      - .env
    networks:
      - traefik-net
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    networks:
      - traefik-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9092:9090"
    restart: unless-stopped
  promtail:
    image: grafana/promtail:latest
    networks:
      - traefik-net
    volumes:
      - ./access_logs:/var/log/traefik
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
  loki:
    image: grafana/loki:latest
    ports:
      - "3200:3100"
      - "9095:9095" # Expose gRPC port
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - ./data/loki:/loki
    networks:
      - traefik-net
    command: 
      - "-config.file=/etc/loki/local-config.yaml"
      - "-validation.allow-structured-metadata=false"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - traefik-net
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
    volumes:
      - ./data/grafana:/var/lib/grafana
networks:
  traefik-net:
    driver: bridge # Docker akan otomatis membuat network ini jika belum ada
