services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: always
    ports:
      - "9090:9080" # Port trafik utama (pengganti APISIX)
      - "18080:8080" # Port Dashboard Traefik
    volumes:
      # Agar Traefik bisa membaca container Docker lain
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # File konfigurasi utama
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      # Folder untuk file routing (perawat, dokter, dev, prod)
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./access_logs:/var/log/traefik
    env_file:
      - .env
    networks:
      - traefik-net
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./access_logs:/var/log/traefik
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
  loki:
    image: grafana/loki:latest
    ports:
      - "3200:3100"
    command: -config.file=/etc/loki/local-config.yaml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
    volumes:
      - ./data/grafana:/var/lib/grafana
networks:
  traefik-net:
    driver: bridge # Docker akan otomatis membuat network ini jika belum ada
