api:
  dashboard: true
  insecure: true

entryPoints:
  traefik:
    address: ":8080"
  web:
    address: ":9080"
    forwardedHeaders:
      trustedIPs:
        - "22.22.22.11/32"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true # <--- Kunci agar perubahan otomatis muncul di dashboard

accessLog:
  format: json # Sangat disarankan pakai JSON agar mudah dibaca Loki
  bufferingSize: 100 # Opsional, untuk performa
  fields:
    defaultMode: keep # Tampilkan semua field default
    headers:
      defaultMode: keep # Tampilkan SEMUA request headers umum
      names:
        Authorization: keep # <--- TAMBAHKAN INI (Paksa Traefik untuk tidak men-drop header ini)

metrics:
  prometheus:
    entryPoint: traefik # Menggunakan port 8080 (dashboard)
    addEntryPointsLabels: true
    addServicesLabels: true

experimental:
  plugins:
    jwt:
      moduleName: github.com/tpaulus/jwt-middleware
      version: v1.1.10
