http:
  middlewares:
    simrs-cors:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Authorization"
          - "Content-Type"
          - "X-Requested-With"
          - "X-Rs-Code"
          - "Req-Id"
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 100
        # Tambahkan baris di bawah ini untuk memastikan header Auth diizinkan
        addVaryHeader: true
  routers:
    mcu_1:
      rule: "PathPrefix(`/v1.0/mcu/order-mcu/get-list`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-mcu
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    mcu_2:
      rule: "PathPrefix(`/v1.0/mcu/order-mcu/get-by-nomor-order/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-mcu
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    mcu_3:
      rule: "PathPrefix(`/v1.0/mcu/order-mcu/get-by-no-registrasi/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-mcu
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    mcu_4:
      rule: "PathPrefix(`/v1.0/mcu/order-mcu/update-diterima`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-mcu
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    mcu_5:
      rule: "PathPrefix(`/v1.0/mcu/order-mcu/update-selesai`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-mcu
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    mcu_6:
      rule: "PathPrefix(`/v1.0/mcu/order-mcu/update-hasil-pemeriksaan`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-mcu
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    mcu_7:
      rule: "PathPrefix(`/v1.0/mcu/order-mcu/update-kesimpulan`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-mcu
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    mcu_8:
      rule: "PathPrefix(`/v1.0/mcu/order-mcu/send-antrian-selesai/`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-mcu
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

  services:
    service-mcu:
      loadBalancer:
        servers:
          - url: "http://192.168.18.152:9103"
