http:
  middlewares:
    simrs-cors:
      headers:
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Authorization"
          - "Content-Type"
          - "X-Requested-With"
          - "X-Rs-Code"
        accessControlAllowOriginList:
          - "*"
        accessControlMaxAge: 100
        # Tambahkan baris di bawah ini untuk memastikan header Auth diizinkan
        addVaryHeader: true
  routers:

  services:
    service-gasmedis:
      loadBalancer:
        servers:
          - url: "http://22.22.22.59:9108"
