http:
  routers:
    gas_medis_detail_1:
      rule: "PathPrefix(`/v1.0/gas-medis/detail-order/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_detail_2:
      rule: "PathPrefix(`/v1.0/gas-medis/detail-order/get-by-nomor-order/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_detail_3:
      rule: "PathPrefix(`/v1.0/gas-medis/detail-order/get-by-kode/`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_detail_4:
      rule: "PathPrefix(`/v1.0/gas-medis/detail-order/generate-kode`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_detail_5:
      rule: "PathPrefix(`/v1.0/gas-medis/detail-order/update`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_detail_6:
      rule: "PathPrefix(`/v1.0/gas-medis/detail-order/delete/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_ordersupplier_1:
      rule: "PathPrefix(`/v1.0/gas-medis/order-supplier/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_ordersupplier_2:
      rule: "PathPrefix(`/v1.0/gas-medis/order-supplier/getlist`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_ordersupplier_3:
      rule: "PathPrefix(`/v1.0/gas-medis/order-supplier/update`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_ordersupplier_4:
      rule: "PathPrefix(`/v1.0/gas-medis/order-supplier/terima-order`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_ordersupplier_5:
      rule: "PathPrefix(`/v1.0/gas-medis/order-supplier/delete/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_ordersupplier_6:
      rule: "PathPrefix(`/v1.0/gas-medis/order-supplier/send-order/`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_list_1:
      rule: "PathPrefix(`/v1.0/gas-medis/gas-medis/getlist`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_order_1:
      rule: "PathPrefix(`/v1.0/gas-medis/order-gas-medis/create`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_order_2:
      rule: "PathPrefix(`/v1.0/gas-medis/order-gas-medis/getlist`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_order_3:
      rule: "PathPrefix(`/v1.0/gas-medis/order-gas-medis/update`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_order_4:
      rule: "PathPrefix(`/v1.0/gas-medis/order-gas-medis/terima-order`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_order_5:
      rule: "PathPrefix(`/v1.0/gas-medis/order-gas-medis/delete/`) && (Method(`DELETE`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_order_6:
      rule: "PathPrefix(`/v1.0/gas-medis/order-gas-medis/send-order/`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_proses_1:
      rule: "PathPrefix(`/v1.0/gas-medis/proses-order-gas-medis/getlist`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_proses_2:
      rule: "PathPrefix(`/v1.0/gas-medis/proses-order-gas-medis/order-disetujui`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_proses_3:
      rule: "PathPrefix(`/v1.0/gas-medis/proses-order-gas-medis/order-ditolak`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_proses_4:
      rule: "PathPrefix(`/v1.0/gas-medis/proses-order-gas-medis/kirim-ke-ruangan`) && (Method(`PUT`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_laporan_1:
      rule: "PathPrefix(`/v1.0/gas-medis/laporan/stok-gas`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_laporan_2:
      rule: "PathPrefix(`/v1.0/gas-medis/laporan/konsumsi-gas-per-unit`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_laporan_3:
      rule: "PathPrefix(`/v1.0/gas-medis/laporan/rekapitulasi-order-unit`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"

    gas_medis_laporan_4:
      rule: "PathPrefix(`/v1.0/gas-medis/laporan/rekapitulasi-order-supplier`) && (Method(`GET`) || Method(`OPTIONS`))"
      service: service-gas-medis
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
  services:
    service-gas-medis:
      loadBalancer:
        servers:
          - url: "${SERVICE_GAS_MEDIS_URL}"
