http:
  routers:
    internal_remun_hitung_1:
      rule: "PathPrefix(`/v1.0/remun/proses-remunerasi-bpjs`) && (Method(`POST`) || Method(`OPTIONS`))"
      service: service-remun-hitung
      entryPoints:
        - web
      middlewares:
        - "simrs-cors"
    services:
      service-remun-hitung:
        loadBalancer:
          servers:
            - url: "http://192.168.18.152:9150"
